#curl ftp://10.48.86.245/NGFW_BOT/ --user calo:calo

'1000':
  asa:
    - /
  ftd:
    - cisco-ftd-fp1k.7.0.0-94.SPA
    - cisco-ftd-fp1k.7.0.4-55.SPA
    - cisco-ftd-fp1k.7.0.6-236.SPA
    - cisco-ftd-fp1k.7.1.0-90.SPA
    - cisco-ftd-fp1k.7.2.0-82.SPA
    - cisco-ftd-fp1k.7.2.1-40.SPA
    - cisco-ftd-fp1k.7.2.2-54.SPA
    - cisco-ftd-fp1k.7.2.3-77.SPA
    - cisco-ftd-fp1k.7.2.4-165.SPA
    - cisco-ftd-fp1k.7.2.5-208.SPA
    - cisco-ftd-fp1k.7.2.6-167.SPA
    - cisco-ftd-fp1k.7.3.0-69.SPA
    - cisco-ftd-fp1k.7.3.1-19.SPA
    - cisco-ftd-fp1k.7.4.1-172.SPA

'2000':
  asa:
    - /
  ftd:
    - cisco-ftd-fp2k.7.0.0-94.SPA
    - cisco-ftd-fp2k.7.0.4-55.SPA
    - cisco-ftd-fp2k.7.0.6-236.SPA
    - cisco-ftd-fp2k.7.2.0-82.SPA
    - cisco-ftd-fp2k.7.2.1-40.SPA
    - cisco-ftd-fp2k.7.2.2-54.SPA
    - cisco-ftd-fp2k.7.2.3-77.SPA
    - cisco-ftd-fp2k.7.2.4-165.SPA
    - cisco-ftd-fp2k.7.2.5-208.SPA
    - cisco-ftd-fp2k.7.2.6-167.SPA
    - cisco-ftd-fp2k.7.3.0-69.SPA
    - cisco-ftd-fp2k.7.3.1-19.SPA
    - cisco-ftd-fp2k.7.4.1-172.SPA

'3105':
  asa:
  ftd:
    - Cisco_FTD_SSP_FP3K_Upgrade-7.3.1-19.sh.REL.tar
    - Cisco_FTD_SSP_FP3K_Upgrade-7.4.1-172.sh.REL.tar

'3100':
  asa:
    -
  ftd:
    - cisco-ftd-fp3k.7.1.0-90.SPA
    - cisco-ftd-fp3k.7.2.5-208.SPA
    - cisco-ftd-fp3k.7.2.7-500.SPA
    - Cisco_FTD_SSP_FP3K_Upgrade-7.3.1-19.sh.REL.tar
    - Cisco_FTD_SSP_FP3K_Upgrade-7.4.1-172.sh.REL.tar




